apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-ui
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello Kubernetes ğŸ‘‹</title>
    </head>
    <body>
      <h1>Hello from Kubernetes ğŸ‘‹</h1>
      <p>Deployed via Argo CD</p>
    </body>
    </html>
